### PR TITLE
Send an email when a new audit request is made

### PR DESCRIPTION
**Pull request by xel1045**
This PR add the sending of an email (feature #16) when a user create a new audit.

### CODE REVIEW

**Comment by tomzx** [comment]
Can you retarget the `develop` branch?

**Comment by xel1045** [comment]
To test it, don't forget to configure your email sending in redmine/config/configuration.yml

**Comment by xel1045** [comment]
How can I do it?

**Comment by tomzx** [comment]
Looks like the only way is to close this one and open a new PR.

**Pull request closed without merging**
