### PR TITLE
Features/16 send an email when a new audit request is made

### LINKED ISSUE #41: Class patch are not correctly applied
Normally, we're suppose to include method to the existing class. Here's an example:

```
require_dependency 'project'

module CodeAudit
    module ProjectPatch
        def self.included(base) # :nodoc:
            base.extend(ClassMethods)
            base.send(:include, InstanceMethods)

            base.class_eval do
                unloadable

                has_many :audits
            end
        end

        module ClassMethods
        end

        module InstanceMethods
        end
    end
end

Project.send(:include, CodeAudit::ProjectPatch) unless Project.included_modules.include? CodeAudit::ProjectPatch
```

### PR DESCRIPTION
**Pull request by xel1045**
- This PR add the sending of an email (feature #16) when a user create a new audit.
- This PR also fixes #41: classes are not correctly patched.

### CODE REVIEW

**Comment by xel1045** [comment]
Yeah! Got it! :)

**Comment by xel1045** [comment]
So, like I was saying : do not forgot to configure your smtp setting to test this feature. You can do it in redmine/config/configuration.yml

**Comment by tomzx** [comment]
I think this will need to be rebased. I'm not sure why you have the 0dbaff2ecee7e5b89daacbcc00dd5dce060daec6 commit in there (the merge).

**Comment by xel1045** [comment]
I just cleanup the code.

**Comment by tomzx** [comment]
In the `Administration - Settings - Email notification`, a new item for `Audit created` should be added to the `Select actions for which email notifications should be sent.` section.

**Comment by tomzx** [comment]
@xel1045 Can you specify which users it is supposed to send the email to? When I tested it, it was sending it to the audit author, which is not very useful.

**Pull request closed without merging**
